export const PROFILE_REQUEST="PROFILE_REQUEST";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";
export const PROFILE_FAILURE="PROFILE_FAILURE";

export const GET_FOLLOWING_REQUEST="GET_FOLLOWING_REQUEST";
export const GET_FOLLOWING_SUCCESS="GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAILURE="GET_FOLLOWING_FAILURE";

export const GET_POST_REQUEST="GET_POST_REQUEST";
export const GET_POST_SUCCESS="GET_POST_SUCCESS";
export const GET_POST_FAILURE="GET_POST_FAILURE";

export const GET_USERS_REQUEST="GET_USERS_REQUEST";
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS";
export const GET_USERS_FAILURE="GET_USERS_FAILURE";

export const GET_USERS_REELS_REQUEST="GET_USERS_REELS_REQUEST";
export const GET_USERS_REELS_SUCCESS="GET_USERS_REELS_SUCCESS";
export const GET_USERS_REELS_FAILURE="GET_USERS_REELS_FAILURE";

export const GET_FOLLOW_REQUEST="GET_FOLLOW_REQUEST";
export const GET_FOLLOW_SUCCESS="GET_FOLLOW_SUCCESS";
export const GET_FOLLOW_FAILURE="GET_FOLLOW_FAILURE";