export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILURE="REGISTER_FAILURE";

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE="UPDATE_PROFILE_FAILURE";

export const SEARCH_USER_REQUEST="SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE="SEARCH_USER_FAILURE";

export const GET_PROFILE_PIC_REQUEST="GET_PROFILE_PIC_REQUEST";
export const GET_PROFILE_PIC_SUCCESS="GET_PROFILE_PIC_SUCCESS";
export const GET_PROFILE_PIC_FAILURE="GET_PROFILE_PIC_FAILURE";

export const CREATE_STORY_REQUEST="CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS="CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE="CREATE_STORY_FAILURE";

export const SELF_STORY_REQUEST="SELF_STORY_REQUEST";
export const SELF_STORY_SUCCESS="SELF_STORY_SUCCESS";
export const SELF_STORY_FAILURE="SELF_STORY_FAILURE";

export const USERS_FOR_STORY_REQUEST="USERS_FOR_STORY_REQUEST";
export const USERS_FOR_STORY_SUCCESS="USERS_FOR_STORY_SUCCESS";
export const USERS_FOR_STORY_FAILURE="USERS_FOR_STORY_FAILURE";

export const USER_STORY_REQUEST="USER_STORY_REQUEST";
export const USER_STORY_SUCCESS="USER_STORY_SUCCESS";
export const USER_STORY_FAILURE="USER_STORY_FAILURE";

export const RESTORE_SESSION="RESTORE_SESSION";
export const CLEAR_SESSION="CLEAR_SESSION";